'use client';

import React, { useState } from 'react';
import { Check, UploadCloud, FileText } from 'lucide-react';
import { cn } from '@/utils/cn';

// UI Components
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';

// 1. Define the data contract for your backend API
export interface EmployeeFormData {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    address: string;
    employeeId: string;
    department: string;
    role: string;
    salary: string;
    joiningDate: string;
}

interface AddEmployeeModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSubmit?: (data: EmployeeFormData) => void;
}

const initialFormState: EmployeeFormData = {
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    address: '',
    employeeId: 'EMP-001', // Usually generated by backend, but kept here for UI
    department: 'Engineering',
    role: 'Frontend Developer',
    salary: '',
    joiningDate: ''
};

export default function AddEmployeeModal({ isOpen, onClose, onSubmit }: AddEmployeeModalProps) {
    const [step, setStep] = useState(1);
    const [formData, setFormData] = useState<EmployeeFormData>(initialFormState);

    // 2. Centralized change handler for all inputs
    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleClose = () => {
        setStep(1);
        setFormData(initialFormState);
        onClose();
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();

        // If we are not on the last step, just move forward
        if (step < 3) {
            setStep(prev => prev + 1);
            return;
        }

        // Final Submission
        if (onSubmit) {
            onSubmit(formData);
        } else {
            console.log('API Payload Ready:', formData);
        }

        handleClose();
    };

    return (
        <Modal isOpen={isOpen} onClose={handleClose} title="Add New Employee" className="max-w-3xl">
            <form onSubmit={handleSubmit} className="flex flex-col">

                {/* Stepper Header */}
                <div className="px-4 pt-2 pb-6">
                    <div className="relative flex items-center justify-between w-full">
                        {/* Connecting Lines */}
                        <div className="absolute left-0 top-1/2 -translate-y-1/2 w-full h-0.5 bg-gray-200 z-0"></div>
                        <div
                            className="absolute left-0 top-1/2 -translate-y-1/2 h-0.5 bg-blue-600 z-0 transition-all duration-300"
                            style={{ width: step === 1 ? '0%' : step === 2 ? '50%' : '100%' }}
                        ></div>

                        {/* Step 1 */}
                        <div className="relative z-10 flex flex-col items-center gap-2 bg-white px-2">
                            <div className={cn(
                                "w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold transition-colors border-2",
                                step >= 1 ? "bg-blue-600 border-blue-600 text-white" : "bg-white border-gray-300 text-gray-400"
                            )}>
                                {step > 1 ? <Check size={16} /> : "1"}
                            </div>
                            <span className={cn("text-xs font-semibold uppercase tracking-wider", step >= 1 ? "text-blue-600" : "text-gray-400")}>Personal Info</span>
                        </div>

                        {/* Step 2 */}
                        <div className="relative z-10 flex flex-col items-center gap-2 bg-white px-2">
                            <div className={cn(
                                "w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold transition-colors border-2",
                                step >= 2 ? "bg-blue-600 border-blue-600 text-white" : "bg-white border-gray-300 text-gray-400"
                            )}>
                                {step > 2 ? <Check size={16} /> : "2"}
                            </div>
                            <span className={cn("text-xs font-semibold uppercase tracking-wider", step >= 2 ? "text-blue-600" : "text-gray-400")}>Job Details</span>
                        </div>

                        {/* Step 3 */}
                        <div className="relative z-10 flex flex-col items-center gap-2 bg-white px-2">
                            <div className={cn(
                                "w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold transition-colors border-2",
                                step >= 3 ? "bg-blue-600 border-blue-600 text-white" : "bg-white border-gray-300 text-gray-400"
                            )}>
                                3
                            </div>
                            <span className={cn("text-xs font-semibold uppercase tracking-wider", step >= 3 ? "text-blue-600" : "text-gray-400")}>Documents</span>
                        </div>
                    </div>
                </div>

                {/* Form Body */}
                <div className="flex-1 p-2">

                    {/* STEP 1: Personal Info */}
                    {step === 1 && (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-5 animate-in fade-in slide-in-from-right-4 duration-300">
                            <Input label="First Name" name="firstName" value={formData.firstName} onChange={handleChange} placeholder="John" required />
                            <Input label="Last Name" name="lastName" value={formData.lastName} onChange={handleChange} placeholder="Doe" required />
                            <Input label="Email" type="email" name="email" value={formData.email} onChange={handleChange} placeholder="john@example.com" required />
                            <Input label="Phone" name="phone" value={formData.phone} onChange={handleChange} placeholder="+1 234 567 890" required />
                            <div className="md:col-span-2">
                                <Input label="Address" name="address" value={formData.address} onChange={handleChange} placeholder="123 Main St, City, Country" required />
                            </div>
                        </div>
                    )}

                    {/* STEP 2: Job Details */}
                    {step === 2 && (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-5 animate-in fade-in slide-in-from-right-4 duration-300">
                            <Input label="Employee ID" name="employeeId" value={formData.employeeId} readOnly className="bg-gray-50 text-gray-500" />

                            <div className="flex flex-col gap-1.5">
                                <label className="text-sm font-medium text-gray-700">Department</label>
                                <select name="department" value={formData.department} onChange={handleChange} className="h-10 px-3 rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-600 text-sm bg-white">
                                    <option value="Engineering">Engineering</option>
                                    <option value="Design">Design</option>
                                    <option value="Product">Product</option>
                                    <option value="HR">HR</option>
                                </select>
                            </div>

                            <div className="flex flex-col gap-1.5">
                                <label className="text-sm font-medium text-gray-700">Role</label>
                                <select name="role" value={formData.role} onChange={handleChange} className="h-10 px-3 rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-600 text-sm bg-white">
                                    <option value="Frontend Developer">Frontend Developer</option>
                                    <option value="Backend Developer">Backend Developer</option>
                                    <option value="UX Designer">UX Designer</option>
                                    <option value="QA Engineer">QA Engineer</option>
                                </select>
                            </div>

                            {/* Custom Input for Salary to keep the $ prefix */}
                            <div className="flex flex-col gap-1.5">
                                <label className="text-sm font-medium text-gray-700">Salary</label>
                                <div className="relative">
                                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 text-sm">$</span>
                                    <input type="text" name="salary" value={formData.salary} onChange={handleChange} placeholder="50,000" className="w-full h-10 pl-7 pr-3 rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-600 text-sm" required />
                                </div>
                            </div>

                            <div className="md:col-span-2">
                                <Input label="Joining Date" type="date" name="joiningDate" value={formData.joiningDate} onChange={handleChange} required />
                            </div>
                        </div>
                    )}

                    {/* STEP 3: Documents */}
                    {step === 3 && (
                        <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                            <div className="border-2 border-dashed border-gray-300 rounded-xl p-8 flex flex-col items-center justify-center text-center hover:bg-gray-50 transition-colors cursor-pointer group">
                                <div className="p-3 bg-blue-50 text-blue-600 rounded-full mb-3 group-hover:scale-110 transition-transform">
                                    <UploadCloud size={24} />
                                </div>
                                <p className="text-sm font-semibold text-gray-900">Upload Profile Photo</p>
                                <p className="text-xs text-gray-500 mt-1">SVG, PNG, JPG or GIF (max. 800x400px)</p>
                            </div>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div className="border border-gray-200 rounded-xl p-4 flex items-center gap-4 hover:border-blue-600 transition-colors cursor-pointer">
                                    <div className="p-2 bg-gray-100 text-gray-500 rounded-lg">
                                        <FileText size={20} />
                                    </div>
                                    <div>
                                        <p className="text-sm font-semibold text-gray-900">ID_Proof.pdf</p>
                                        <p className="text-xs text-blue-600 mt-0.5 font-medium">Tap to upload</p>
                                    </div>
                                </div>
                                <div className="border border-gray-200 rounded-xl p-4 flex items-center gap-4 hover:border-blue-600 transition-colors cursor-pointer">
                                    <div className="p-2 bg-gray-100 text-gray-500 rounded-lg">
                                        <FileText size={20} />
                                    </div>
                                    <div>
                                        <p className="text-sm font-semibold text-gray-900">Offer_Letter.pdf</p>
                                        <p className="text-xs text-blue-600 mt-0.5 font-medium">Tap to upload</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                {/* Footer Controls */}
                <div className="pt-6 mt-6 border-t border-gray-100 flex items-center justify-between">
                    {step === 1 ? (
                        <Button type="button" variant="ghost" onClick={handleClose}>
                            Cancel
                        </Button>
                    ) : (
                        <Button type="button" variant="outline" onClick={() => setStep(step - 1)}>
                            Previous
                        </Button>
                    )}

                    <Button type="submit" variant="primary">
                        {step < 3 ? 'Next' : 'Submit'}
                    </Button>
                </div>
            </form>
        </Modal>
    );
}